-- CORPUS 0008 — RBAC reference data.
--
-- GENERATED FILE. Do not edit by hand.
-- Source of truth: packages/domain/src/roles.ts
-- Regenerate:     npx tsx scripts/generate-rbac-migration.ts

PRAGMA foreign_keys = ON;

INSERT OR REPLACE INTO roles (code, name, description) VALUES
  ('EMPLOYEE', 'EMPLOYEE', 'Verified employee — self-service only'),
  ('MANAGER', 'MANAGER', 'People manager — self plus direct reports'),
  ('HR', 'HR', 'HR generalist — organisation-wide HR operations'),
  ('HR_ADMIN', 'HR ADMIN', 'HR administrator — includes compensation, audit and security read'),
  ('SYSTEM_ADMIN', 'SYSTEM ADMIN', 'Platform administrator — full explicit permission set');

INSERT OR REPLACE INTO permissions (code, description) VALUES
  ('employee.read.self', 'Read own employee record'),
  ('employee.read.team', 'Read direct reports'),
  ('employee.read.all', 'Read all employees in the tenant'),
  ('employee.create', 'Create employee records'),
  ('employee.update', 'Update employee records'),
  ('employee.read.compensation', 'Read RESTRICTED compensation data'),
  ('leave.read.self', 'Read own leave'),
  ('leave.read.team', 'Read direct reports leave'),
  ('leave.read.all', 'Read all leave in the tenant'),
  ('leave.create.self', 'Submit own leave request'),
  ('leave.cancel.self', 'Cancel own leave request'),
  ('leave.approve.team', 'Approve or reject direct reports leave'),
  ('leave.approve.all', 'Approve or reject any leave'),
  ('leave.manage', 'Manage leave types, balances and holidays'),
  ('job.read.public', 'Read published jobs'),
  ('job.read.internal', 'Read draft and closed jobs'),
  ('job.create', 'Create jobs'),
  ('job.update', 'Update jobs'),
  ('job.delete', 'Delete or archive jobs'),
  ('candidate.read', 'Read candidate records'),
  ('candidate.update', 'Update candidate records'),
  ('candidate.create.public', 'Create a candidate record via public application'),
  ('application.read', 'Read applications'),
  ('application.read.self', 'Read own application status'),
  ('application.create.public', 'Submit a public application'),
  ('application.update', 'Update application stage'),
  ('interview.read', 'Read interviews'),
  ('interview.manage', 'Schedule and evaluate interviews'),
  ('offer.read', 'Read offers'),
  ('offer.manage', 'Create and manage offers'),
  ('policy.read', 'Read INTERNAL knowledge documents'),
  ('policy.read.confidential', 'Read CONFIDENTIAL knowledge documents'),
  ('policy.read.restricted', 'Read RESTRICTED knowledge documents'),
  ('policy.create', 'Create knowledge documents'),
  ('policy.update', 'Update knowledge documents'),
  ('policy.delete', 'Delete or archive knowledge documents'),
  ('faq.read.public', 'Read PUBLIC curated bot answers as an anonymous candidate'),
  ('faq.read', 'Read curated bot answers for the internal zone'),
  ('faq.manage', 'Author, publish and archive curated bot answers'),
  ('report.read', 'Read HR reports and analytics'),
  ('audit.read', 'Read the audit trail'),
  ('security.read', 'Read security events'),
  ('system.manage', 'Manage tenants, users and roles');

-- Role → permission grants. No wildcards: SYSTEM_ADMIN is fully enumerated
-- so every grant stays visible in the audit trail.
DELETE FROM role_permissions;
INSERT INTO role_permissions (role_code, permission_code) VALUES
  ('EMPLOYEE', 'employee.read.self'),
  ('EMPLOYEE', 'leave.read.self'),
  ('EMPLOYEE', 'leave.create.self'),
  ('EMPLOYEE', 'leave.cancel.self'),
  ('EMPLOYEE', 'policy.read'),
  ('EMPLOYEE', 'faq.read'),
  ('EMPLOYEE', 'job.read.internal'),
  ('EMPLOYEE', 'job.read.public'),
  ('MANAGER', 'employee.read.self'),
  ('MANAGER', 'employee.read.team'),
  ('MANAGER', 'leave.read.self'),
  ('MANAGER', 'leave.read.team'),
  ('MANAGER', 'leave.create.self'),
  ('MANAGER', 'leave.cancel.self'),
  ('MANAGER', 'leave.approve.team'),
  ('MANAGER', 'policy.read'),
  ('MANAGER', 'faq.read'),
  ('MANAGER', 'job.read.internal'),
  ('MANAGER', 'job.read.public'),
  ('MANAGER', 'interview.read'),
  ('MANAGER', 'report.read'),
  ('HR', 'employee.read.self'),
  ('HR', 'employee.read.team'),
  ('HR', 'employee.read.all'),
  ('HR', 'employee.update'),
  ('HR', 'leave.read.self'),
  ('HR', 'leave.read.team'),
  ('HR', 'leave.read.all'),
  ('HR', 'leave.create.self'),
  ('HR', 'leave.cancel.self'),
  ('HR', 'leave.approve.all'),
  ('HR', 'leave.manage'),
  ('HR', 'policy.read'),
  ('HR', 'policy.read.confidential'),
  ('HR', 'policy.create'),
  ('HR', 'policy.update'),
  ('HR', 'faq.read'),
  ('HR', 'faq.manage'),
  ('HR', 'job.read.public'),
  ('HR', 'job.read.internal'),
  ('HR', 'job.create'),
  ('HR', 'job.update'),
  ('HR', 'candidate.read'),
  ('HR', 'candidate.update'),
  ('HR', 'application.read'),
  ('HR', 'application.update'),
  ('HR', 'interview.read'),
  ('HR', 'interview.manage'),
  ('HR', 'offer.read'),
  ('HR', 'report.read'),
  ('HR_ADMIN', 'employee.read.self'),
  ('HR_ADMIN', 'employee.read.team'),
  ('HR_ADMIN', 'employee.read.all'),
  ('HR_ADMIN', 'employee.create'),
  ('HR_ADMIN', 'employee.update'),
  ('HR_ADMIN', 'employee.read.compensation'),
  ('HR_ADMIN', 'leave.read.self'),
  ('HR_ADMIN', 'leave.read.team'),
  ('HR_ADMIN', 'leave.read.all'),
  ('HR_ADMIN', 'leave.create.self'),
  ('HR_ADMIN', 'leave.cancel.self'),
  ('HR_ADMIN', 'leave.approve.all'),
  ('HR_ADMIN', 'leave.manage'),
  ('HR_ADMIN', 'policy.read'),
  ('HR_ADMIN', 'policy.read.confidential'),
  ('HR_ADMIN', 'policy.read.restricted'),
  ('HR_ADMIN', 'policy.create'),
  ('HR_ADMIN', 'policy.update'),
  ('HR_ADMIN', 'policy.delete'),
  ('HR_ADMIN', 'faq.read'),
  ('HR_ADMIN', 'faq.manage'),
  ('HR_ADMIN', 'job.read.public'),
  ('HR_ADMIN', 'job.read.internal'),
  ('HR_ADMIN', 'job.create'),
  ('HR_ADMIN', 'job.update'),
  ('HR_ADMIN', 'job.delete'),
  ('HR_ADMIN', 'candidate.read'),
  ('HR_ADMIN', 'candidate.update'),
  ('HR_ADMIN', 'application.read'),
  ('HR_ADMIN', 'application.update'),
  ('HR_ADMIN', 'interview.read'),
  ('HR_ADMIN', 'interview.manage'),
  ('HR_ADMIN', 'offer.read'),
  ('HR_ADMIN', 'offer.manage'),
  ('HR_ADMIN', 'report.read'),
  ('HR_ADMIN', 'audit.read'),
  ('HR_ADMIN', 'security.read'),
  ('SYSTEM_ADMIN', 'employee.read.self'),
  ('SYSTEM_ADMIN', 'employee.read.team'),
  ('SYSTEM_ADMIN', 'employee.read.all'),
  ('SYSTEM_ADMIN', 'employee.create'),
  ('SYSTEM_ADMIN', 'employee.update'),
  ('SYSTEM_ADMIN', 'employee.read.compensation'),
  ('SYSTEM_ADMIN', 'leave.read.self'),
  ('SYSTEM_ADMIN', 'leave.read.team'),
  ('SYSTEM_ADMIN', 'leave.read.all'),
  ('SYSTEM_ADMIN', 'leave.create.self'),
  ('SYSTEM_ADMIN', 'leave.cancel.self'),
  ('SYSTEM_ADMIN', 'leave.approve.team'),
  ('SYSTEM_ADMIN', 'leave.approve.all'),
  ('SYSTEM_ADMIN', 'leave.manage'),
  ('SYSTEM_ADMIN', 'job.read.public'),
  ('SYSTEM_ADMIN', 'job.read.internal'),
  ('SYSTEM_ADMIN', 'job.create'),
  ('SYSTEM_ADMIN', 'job.update'),
  ('SYSTEM_ADMIN', 'job.delete'),
  ('SYSTEM_ADMIN', 'candidate.read'),
  ('SYSTEM_ADMIN', 'candidate.update'),
  ('SYSTEM_ADMIN', 'candidate.create.public'),
  ('SYSTEM_ADMIN', 'application.read'),
  ('SYSTEM_ADMIN', 'application.read.self'),
  ('SYSTEM_ADMIN', 'application.create.public'),
  ('SYSTEM_ADMIN', 'application.update'),
  ('SYSTEM_ADMIN', 'interview.read'),
  ('SYSTEM_ADMIN', 'interview.manage'),
  ('SYSTEM_ADMIN', 'offer.read'),
  ('SYSTEM_ADMIN', 'offer.manage'),
  ('SYSTEM_ADMIN', 'policy.read'),
  ('SYSTEM_ADMIN', 'policy.read.confidential'),
  ('SYSTEM_ADMIN', 'policy.read.restricted'),
  ('SYSTEM_ADMIN', 'policy.create'),
  ('SYSTEM_ADMIN', 'policy.update'),
  ('SYSTEM_ADMIN', 'policy.delete'),
  ('SYSTEM_ADMIN', 'faq.read.public'),
  ('SYSTEM_ADMIN', 'faq.read'),
  ('SYSTEM_ADMIN', 'faq.manage'),
  ('SYSTEM_ADMIN', 'report.read'),
  ('SYSTEM_ADMIN', 'audit.read'),
  ('SYSTEM_ADMIN', 'security.read'),
  ('SYSTEM_ADMIN', 'system.manage');
